books/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views


urlpatterns = [
    url(r'^$',
        login_required(views.DashboardView.as_view()),
        name="dashboard"),

    # Organizations
    url(r'^organization/$',
        login_required(views.OrganizationListView.as_view()),
        name="organization-list"),
    url(r'^organization/selector/$',
        login_required(views.OrganizationSelectorView.as_view()),
        name="organization-selector"),
    url(r'^organization/create/$',
        login_required(views.OrganizationCreateView.as_view()),
        name="organization-create"),
    url(r'^organization/(?P<pk>\d+)/edit/$',
        login_required(views.OrganizationUpdateView.as_view()),
        name="organization-edit"),
    url(r'^organization/(?P<pk>\d+)/detail/$',
        login_required(views.OrganizationDetailView.as_view()),
        name="organization-detail"),
    url(r'^organization/(?P<pk>\d+)/select/$',
        login_required(views.OrganizationSelectionView.as_view()),
        name="organization-select"),

    # Tax Rates
    url(r'^tax_rates/$',
        login_required(views.TaxRateListView.as_view()),
        name="tax_rate-list"),
    url(r'^tax_rates/create/$',
        login_required(views.TaxRateCreateView.as_view()),
        name="tax_rate-create"),
    url(r'^tax_rates/(?P<pk>\d+)/edit/$',
        login_required(views.TaxRateUpdateView.as_view()),
        name="tax_rate-edit"),
    url(r'^tax_rates/(?P<pk>\d+)/delete/$',
        login_required(views.TaxRateDeleteView.as_view()),
        name="tax_rate-delete"),

    # Estimates
    url(r'^estimate/$',
        login_required(views.EstimateListView.as_view()),
        name="estimate-list"),
    url(r'^estimate/create/$',
        login_required(views.EstimateCreateView.as_view()),
        name="estimate-create"),
    url(r'^estimate/(?P<pk>\d+)/edit/$',
        login_required(views.EstimateUpdateView.as_view()),
        name="estimate-edit"),
    url(r'^estimate/(?P<pk>\d+)/delete/$',
        login_required(views.EstimateDeleteView.as_view()),
        name="estimate-delete"),
    url(r'^estimate/(?P<pk>\d+)/detail/$',
        login_required(views.EstimateDetailView.as_view()),
        name="estimate-detail"),

    # Invoices
    url(r'^invoice/$',
        login_required(views.InvoiceListView.as_view()),
        name="invoice-list"),
    url(r'^invoice/create/$',
        login_required(views.InvoiceCreateView.as_view()),
        name="invoice-create"),
    url(r'^invoice/(?P<pk>\d+)/edit/$',
        login_required(views.InvoiceUpdateView.as_view()),
        name="invoice-edit"),
    url(r'^invoice/(?P<pk>\d+)/delete/$',
        login_required(views.InvoiceDeleteView.as_view()),
        name="invoice-delete"),
    url(r'^invoice/(?P<pk>\d+)/detail/$',
        login_required(views.InvoiceDetailView.as_view()),
        name="invoice-detail"),

    # Bills
    url(r'^bill/$',
        login_required(views.BillListView.as_view()),
        name="bill-list"),
    url(r'^bill/create/$',
        login_required(views.BillCreateView.as_view()),
        name="bill-create"),
    url(r'^bill/(?P<pk>\d+)/edit/$',
        login_required(views.BillUpdateView.as_view()),
        name="bill-edit"),
    url(r'^bill/(?P<pk>\d+)/delete/$',
        login_required(views.BillDeleteView.as_view()),
        name="bill-delete"),
    url(r'^bill/(?P<pk>\d+)/detail/$',
        login_required(views.BillDetailView.as_view()),
        name="bill-detail"),

    # ExpenseClaims
    url(r'^expense-claim/$',
        login_required(views.ExpenseClaimListView.as_view()),
        name="expense_claim-list"),
    url(r'^expense-claim/create/$',
        login_required(views.ExpenseClaimCreateView.as_view()),
        name="expense_claim-create"),
    url(r'^expense-claim/(?P<pk>\d+)/edit/$',
        login_required(views.ExpenseClaimUpdateView.as_view()),
        name="expense_claim-edit"),
    url(r'^expense-claim/(?P<pk>\d+)/delete/$',
        login_required(views.ExpenseClaimDeleteView.as_view()),
        name="expense_claim-delete"),
    url(r'^expense-claim/(?P<pk>\d+)/detail/$',
        login_required(views.ExpenseClaimDetailView.as_view()),
        name="expense_claim-detail"),

    # Payments
    url(r'^payment/(?P<pk>\d+)/edit/$',
        login_required(views.PaymentUpdateView.as_view()),
        name="payment-edit"),
    url(r'^payment/(?P<pk>\d+)/delete/$',
        login_required(views.PaymentDeleteView.as_view()),
        name="payment-delete"),

    # Items
    url(r'^item/$', views.item_list, name="item-list"),
    url(r'^item/create/$', views.item_create, name="item-create"),
    url(r'^item/(?P<pk>\d+)/edit/$', login_required(views.ItemUpdateView.as_view()), name="item-edit"),
    url(r'^item/(?P<pk>\d+)/delete/$', views.item_delete, name="item-delete"),

    # ajax urls
    url(r'^ajax/item/autocomplete/$', views.item_autocomplete, name='item-autocomplete'),
    url(r'^ajax/item/get-id/', views.item_get_data, name='item-get-data'),
]

config/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views
from books import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', views.logoutnlogin, name='logout'),
    url(r'^', include('connect.urls',
                      namespace="connect")),
    url(r'^books/', include('books.urls',
                            namespace="books")),
    url(r'^people/', include('people.urls',
                             namespace="people")),
    url(r'^reports/', include('reports.urls',
                              namespace="reports")),

    # Printing Bill
    url(r'^bill/(?P<pk>\d+)/GST/$', login_required(views.Print_Bill.as_view()), name="bill_gst"),

    # third party
    url(r'^select2/', include('django_select2.urls')),
]

people/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    # Clients
    url(r'^client/$',
        views.ClientListView.as_view(),
        name="client-list"),
    url(r'^client/create/$',
        views.ClientCreateView.as_view(),
        name="client-create"),
    url(r'^client/(?P<pk>\d+)/edit/$',
        views.ClientUpdateView.as_view(),
        name="client-edit"),
    url(r'^client/(?P<pk>\d+)/detail/$',
        views.ClientDetailView.as_view(),
        name="client-detail"),

    # Employees
    url(r'^employee/$',
        views.EmployeeListView.as_view(),
        name="employee-list"),
    url(r'^employee/create/$',
        views.EmployeeCreateView.as_view(),
        name="employee-create"),
    url(r'^employee/(?P<pk>\d+)/edit/$',
        views.EmployeeUpdateView.as_view(),
        name="employee-edit"),
    url(r'^employee/(?P<pk>\d+)/detail/$',
        views.EmployeeDetailView.as_view(),
        name="employee-detail"),
]

people/models.py
from decimal import Decimal as D

from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator


class Client(models.Model):
    name = models.CharField(max_length=150)

    # address
    address_line_1 = models.CharField(max_length=128)
    address_line_2 = models.CharField(max_length=128,
                                      blank=True, null=True)
    city = models.CharField(max_length=64)
    postal_code = models.CharField(max_length=256)
    country = models.CharField(max_length=50)

    organization = models.ForeignKey('books.Organization',
                                     related_name="clients")

    class Meta:
        pass

    def __str__(self):
        return self.name

    def active_address_fields(self):
        """
        Return the non-empty components of the address
        """
        fields = [self.address_line_1, self.address_line_2,
                  self.city, self.postal_code, self.country]
        fields = [f.strip() for f in fields if f]
        return fields

    def full_address(self, separator="\n"):
        return separator.join(filter(bool, self.active_address_fields()))


class Employee(models.Model):
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.EmailField(max_length=254)

    payroll_tax_rate = models.DecimalField(
        max_digits=6,
        decimal_places=5,
        validators=[
            MinValueValidator(D('0')),
            MaxValueValidator(D('1'))
        ]
    )

    salary_follows_profits = models.BooleanField(default=False)
    shares_percentage = models.DecimalField(
        max_digits=6,
        decimal_places=5,
        validators=[
            MinValueValidator(D('0')),
            MaxValueValidator(D('1'))
        ]
    )

    organization = models.ForeignKey('books.Organization',
                                     related_name="employees")

    class Meta:
        pass

    def __str__(self):
        return "{}".format(self.composite_name)

    @property
    def composite_name(self):
        return "{} {}".format(self.first_name, self.last_name)

people/forms.py
from django.forms import ModelForm
from django.contrib.auth import get_user_model

from .models import Client, Employee

from django_select2.fields import (
    AutoModelSelect2Field,
    AutoModelSelect2MultipleField)


class ClientForm(ModelForm):
    class Meta:
        model = Client
        fields = (
            "name",
            "address_line_1",
            "address_line_2",
            "city",
            "postal_code",
            "country",
        )


class EmployeeForm(ModelForm):
    class Meta:
        model = Employee
        fields = (
            "first_name",
            "last_name",
            "email",

            "payroll_tax_rate",

            "salary_follows_profits",
            "shares_percentage",

        )


# TODO: avoid calling this in the global scope, can lead to circular imports
User = get_user_model()


class UserChoices(AutoModelSelect2Field):
    queryset = User.objects.all()
    search_fields = (
        'first_name__icontains',
        'last_name__icontains',
        'username__icontains',
        'email__icontains',
    )


class UserMultipleChoices(AutoModelSelect2MultipleField):
    queryset = User.objects.all()
    search_fields = (
        'first_name__icontains',
        'last_name__icontains',
        'username__icontains',
        'email__icontains',
    )

people/views.py
from django.views import generic
from django.core.urlresolvers import reverse

from books.mixins import (
    RestrictToSelectedOrganizationQuerySetMixin,
    AutoSetSelectedOrganizationMixin)
from .models import Client, Employee
from .forms import ClientForm, EmployeeForm
from books.utils import organization_manager


class ClientListView(RestrictToSelectedOrganizationQuerySetMixin,
                     generic.ListView):
    template_name = "people/client_list.html"
    model = Client
    context_object_name = "clients"


class ClientCreateView(AutoSetSelectedOrganizationMixin,
                       generic.CreateView):
    template_name = "people/client_create_or_update.html"
    model = Client
    form_class = ClientForm

    def get_success_url(self):
        return reverse("people:client-list")


class ClientUpdateView(RestrictToSelectedOrganizationQuerySetMixin,
                       AutoSetSelectedOrganizationMixin,
                       generic.UpdateView):
    template_name = "people/client_create_or_update.html"
    model = Client
    form_class = ClientForm

    def get_success_url(self):
        return reverse("people:client-list")


class ClientDetailView(RestrictToSelectedOrganizationQuerySetMixin,
                       generic.DetailView):
    template_name = "people/client_detail.html"
    model = Client
    context_object_name = "client"


class EmployeeListView(RestrictToSelectedOrganizationQuerySetMixin,
                       generic.ListView):
    template_name = "people/employee_list.html"
    model = Employee
    context_object_name = "employees"


class EmployeeCreateView(AutoSetSelectedOrganizationMixin,
                         generic.CreateView):
    template_name = "people/employee_create_or_update.html"
    model = Employee
    form_class = EmployeeForm

    def get_success_url(self):
        return reverse("people:employee-list")


class EmployeeUpdateView(RestrictToSelectedOrganizationQuerySetMixin,
                         AutoSetSelectedOrganizationMixin,
                         generic.UpdateView):
    template_name = "people/employee_create_or_update.html"
    model = Employee
    form_class = EmployeeForm

    def get_success_url(self):
        return reverse("people:employee-list")


class EmployeeDetailView(RestrictToSelectedOrganizationQuerySetMixin,
                         generic.DetailView):
    template_name = "people/employee_detail.html"
    model = Employee
    context_object_name = "employee"

templates/people/client_create_or_update.html
{% extends "_generics/form.html" %}

templates/people/client_list.html
{% extends "layout.html" %}

{% block content %}
    <h1 class="page-header">Clients <small>which belong to you</small></h1>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th class="text-right">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for cli in clients %}
            <tr>
                <td>{{ cli.id }}</td>
                <td>{{ cli.name }}</td>
                <td class="text-right">
                    <a href="{% url 'people:client-edit' cli.pk %}" class="btn btn-default btn-sm" role="button">Edit</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <a href="{% url 'people:client-create' %}" class="btn btn-primary btn-lg" role="button">
        Add a client
    </a>
{% endblock content %}

templates/people/employee_create_or_update.html
{% extends "layout.html" %}
{% load bootstrap3 introspection_filters widget_tweaks %}

{% block head %}
    {{ block.super }}
    {{ form.media }}
{% endblock %}

{% block content %}
    {% if object.pk %}
        <h1 class="page-header">Edit a {{ form|get_form_model_verbose_name }}</h1>
    {% else %}
        <h1 class="page-header">Create a {{ form|get_form_model_verbose_name }}</h1>
    {% endif %}

    <form action="." method="post" class="form">
        {% csrf_token %}

        {% if form.non_field_errors %}
        <div class="alert alert-danger" role="alert">
            {% for error in form.non_field_errors %}
            <p {% if forloop.last %} class="mb-0" {% endif %}>{{ error }}</p>
            {% endfor %}
        </div>
        {% endif %}
        
        {{ form.first_name.label_tag }}
        {% render_field form.first_name class="form-control" %}
        <br>
        {{ form.last_name.label_tag }}
        {% render_field form.last_name class="form-control" %}
        <br>
        {{ form.email.label_tag }}
        {% render_field form.email class="form-control" %}
        <br>
        {{ form.payroll_tax_rate.label_tag }}
        {% render_field form.payroll_tax_rate class="form-control" %}
        <br>
        {{ form.salary_follows_profits.label_tag }}
        <input type="checkbox" name="salary_follows_profits" id="salary_follows_profits">
        <br>
        {{ form.shares_percentage.label_tag }}
        {% render_field form.shares_percentage class="form-control" %}
        <br>
        {% buttons %}
            <button type="submit" class="btn btn-success">
                {% if object.pk %}
                    {% bootstrap_icon "hand-right" %} Save changes
                {% else %}
                    {% bootstrap_icon "thumbs-up" %} Send creation
                {% endif %}
            </button>
        {% endbuttons %}
    </form>
{% endblock content %}

templates/people/employee_list.html
{% extends "layout.html" %}

{% block content %}
    <h1 class="page-header">Employees <small>which belong to you</small></h1>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>#</th>
                <th>First name</th>
                <th>Last name</th>
                <th>Email</th>
                <th class="text-right">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for emp in employees %}
            <tr>
                <td>{{ emp.id }}</td>
                <td>{{ emp.first_name }}</td>
                <td>{{ emp.last_name }}</td>
                <td>{{ emp.email }}</td>
                <td class="text-right">
                    <a href="{% url 'people:employee-edit' emp.pk %}" class="btn btn-default btn-sm" role="button">Edit</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <a href="{% url 'people:employee-create' %}" class="btn btn-primary btn-lg" role="button">
        Add an employee
    </a>
{% endblock content %}