books/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views


urlpatterns = [
    url(r'^$',
        login_required(views.DashboardView.as_view()),
        name="dashboard"),

    # Organizations
    url(r'^organization/$',
        login_required(views.OrganizationListView.as_view()),
        name="organization-list"),
    url(r'^organization/selector/$',
        login_required(views.OrganizationSelectorView.as_view()),
        name="organization-selector"),
    url(r'^organization/create/$',
        login_required(views.OrganizationCreateView.as_view()),
        name="organization-create"),
    url(r'^organization/(?P<pk>\d+)/edit/$',
        login_required(views.OrganizationUpdateView.as_view()),
        name="organization-edit"),
    url(r'^organization/(?P<pk>\d+)/detail/$',
        login_required(views.OrganizationDetailView.as_view()),
        name="organization-detail"),
    url(r'^organization/(?P<pk>\d+)/select/$',
        login_required(views.OrganizationSelectionView.as_view()),
        name="organization-select"),

    # Tax Rates
    url(r'^tax_rates/$',
        login_required(views.TaxRateListView.as_view()),
        name="tax_rate-list"),
    url(r'^tax_rates/create/$',
        login_required(views.TaxRateCreateView.as_view()),
        name="tax_rate-create"),
    url(r'^tax_rates/(?P<pk>\d+)/edit/$',
        login_required(views.TaxRateUpdateView.as_view()),
        name="tax_rate-edit"),
    url(r'^tax_rates/(?P<pk>\d+)/delete/$',
        login_required(views.TaxRateDeleteView.as_view()),
        name="tax_rate-delete"),

    # Estimates
    url(r'^estimate/$',
        login_required(views.EstimateListView.as_view()),
        name="estimate-list"),
    url(r'^estimate/create/$',
        login_required(views.EstimateCreateView.as_view()),
        name="estimate-create"),
    url(r'^estimate/(?P<pk>\d+)/edit/$',
        login_required(views.EstimateUpdateView.as_view()),
        name="estimate-edit"),
    url(r'^estimate/(?P<pk>\d+)/delete/$',
        login_required(views.EstimateDeleteView.as_view()),
        name="estimate-delete"),
    url(r'^estimate/(?P<pk>\d+)/detail/$',
        login_required(views.EstimateDetailView.as_view()),
        name="estimate-detail"),

    # Invoices
    url(r'^invoice/$',
        login_required(views.InvoiceListView.as_view()),
        name="invoice-list"),
    url(r'^invoice/create/$',
        login_required(views.InvoiceCreateView.as_view()),
        name="invoice-create"),
    url(r'^invoice/(?P<pk>\d+)/edit/$',
        login_required(views.InvoiceUpdateView.as_view()),
        name="invoice-edit"),
    url(r'^invoice/(?P<pk>\d+)/delete/$',
        login_required(views.InvoiceDeleteView.as_view()),
        name="invoice-delete"),
    url(r'^invoice/(?P<pk>\d+)/detail/$',
        login_required(views.InvoiceDetailView.as_view()),
        name="invoice-detail"),

    # Bills
    url(r'^bill/$',
        login_required(views.BillListView.as_view()),
        name="bill-list"),
    url(r'^bill/create/$',
        login_required(views.BillCreateView.as_view()),
        name="bill-create"),
    url(r'^bill/(?P<pk>\d+)/edit/$',
        login_required(views.BillUpdateView.as_view()),
        name="bill-edit"),
    url(r'^bill/(?P<pk>\d+)/delete/$',
        login_required(views.BillDeleteView.as_view()),
        name="bill-delete"),
    url(r'^bill/(?P<pk>\d+)/detail/$',
        login_required(views.BillDetailView.as_view()),
        name="bill-detail"),

    # ExpenseClaims
    url(r'^expense-claim/$',
        login_required(views.ExpenseClaimListView.as_view()),
        name="expense_claim-list"),
    url(r'^expense-claim/create/$',
        login_required(views.ExpenseClaimCreateView.as_view()),
        name="expense_claim-create"),
    url(r'^expense-claim/(?P<pk>\d+)/edit/$',
        login_required(views.ExpenseClaimUpdateView.as_view()),
        name="expense_claim-edit"),
    url(r'^expense-claim/(?P<pk>\d+)/delete/$',
        login_required(views.ExpenseClaimDeleteView.as_view()),
        name="expense_claim-delete"),
    url(r'^expense-claim/(?P<pk>\d+)/detail/$',
        login_required(views.ExpenseClaimDetailView.as_view()),
        name="expense_claim-detail"),

    # Payments
    url(r'^payment/(?P<pk>\d+)/edit/$',
        login_required(views.PaymentUpdateView.as_view()),
        name="payment-edit"),
    url(r'^payment/(?P<pk>\d+)/delete/$',
        login_required(views.PaymentDeleteView.as_view()),
        name="payment-delete"),

    # Items
    url(r'^item/$', views.item_list, name="item-list"),
    url(r'^item/create/$', views.item_create, name="item-create"),
    url(r'^item/(?P<pk>\d+)/edit/$', login_required(views.ItemUpdateView.as_view()), name="item-edit"),
    url(r'^item/(?P<pk>\d+)/delete/$', views.item_delete, name="item-delete"),

    # ajax urls
    url(r'^ajax/item/autocomplete/$', views.item_autocomplete, name='item-autocomplete'),
    url(r'^ajax/item/get-id/', views.item_get_data, name='item-get-data'),
]

config/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views
from books import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', views.logoutnlogin, name='logout'),
    url(r'^', include('connect.urls',
                      namespace="connect")),
    url(r'^books/', include('books.urls',
                            namespace="books")),
    url(r'^people/', include('people.urls',
                             namespace="people")),
    url(r'^reports/', include('reports.urls',
                              namespace="reports")),

    # Printing Bill
    url(r'^bill/(?P<pk>\d+)/GST/$', login_required(views.Print_Bill.as_view()), name="bill_gst"),

    # third party
    url(r'^select2/', include('django_select2.urls')),
]

books/views.py
import logging
import json
from decimal import Decimal as D
from . import forms

from django.views import generic
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import logout_then_login
from django.core import serializers
from django.core.urlresolvers import reverse, reverse_lazy
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.utils.decorators import method_decorator
from django.shortcuts import get_object_or_404, render
from django.db.models import Sum
from django.http import HttpResponseRedirect

from .mixins import (
    RestrictToSelectedOrganizationQuerySetMixin,
    SaleListQuerySetMixin,
    AutoSetSelectedOrganizationMixin,
    AbstractSaleCreateUpdateMixin,
    AbstractSaleDetailMixin,
    PaymentFormMixin)
from .models import (
    Organization,
    TaxRate,
    Estimate,
    Invoice,
    Item,
    Bill,
    ExpenseClaim,
    Payment)
from .forms import (
    ItemForm,
    OrganizationForm,
    TaxRateForm,
    EstimateForm,
    EstimateLineFormSet,
    InvoiceForm,
    InvoiceLineFormSet,
    BillForm,
    BillLineFormSet,
    ExpenseClaimForm,
    ExpenseClaimLineFormSet,
    PaymentForm)
from .utils import (
    organization_manager,
    EstimateNumberGenerator,
    InvoiceNumberGenerator,
    BillNumberGenerator,
    ExpenseClaimNumberGenerator)
from people.models import Client, Employee

logger = logging.getLogger(__name__)


class OrganizationSelectorView(generic.TemplateView):
    template_name = "books/organization_selector.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        user = self.request.user
        orgas = organization_manager.get_user_organizations(user)
        cumulated_turnovers = (orgas
            .aggregate(sum=Sum('invoices__total_excl_tax'))["sum"]) or D('0')
        cumulated_debts = (orgas
            .aggregate(sum=Sum('bills__total_excl_tax'))["sum"]) or D('0')
        cumulated_profits = cumulated_turnovers - cumulated_debts

        context["organizations_count"] = orgas.count()
        context["organizations_cumulated_turnovers"] = cumulated_turnovers
        context["organizations_cumulated_profits"] = cumulated_profits
        context["organizations_cumulated_active_days"] = 0

        context["organizations"] = orgas
        context["last_invoices"] = Invoice.objects.all()[:10]

        return context


def logoutnlogin(request):
    """Logout n login back"""
    return logout_then_login(request, login_url='login')
    

class DashboardView(generic.DetailView):
    template_name = "books/dashboard.html"
    model = Organization
    context_object_name = "organization"

    def get_object(self):
        return organization_manager.get_selected_organization(self.request)

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        organization = self.get_object()
        ctx['invoices'] = (organization.invoices.all()
            .select_related(
                'client',
                'organization')
            .prefetch_related(
                'lines',
                'lines__tax_rate',
                'payments')
            .distinct())
        ctx['bills'] = (organization.bills.all()
            .select_related(
                'client',
                'organization')
            .prefetch_related(
                'lines',
                'lines__tax_rate',
                'payments')
            .distinct())
        return ctx

    def get(self, request, *args, **kwargs):
        orga = organization_manager.get_selected_organization(self.request)
        if orga is None:
            return HttpResponseRedirect(reverse('books:organization-selector'))
        return super().get(request, *args, **kwargs)


class OrganizationListView(generic.ListView):
    template_name = "books/organization_list.html"
    model = Organization
    context_object_name = "organizations"

    def get_queryset(self):
        # only current authenticated user organizations
        return organization_manager.get_user_organizations(self.request.user)


class OrganizationCreateView(generic.CreateView):
    template_name = "books/organization_create_or_update.html"
    model = Organization
    form_class = OrganizationForm
    success_url = reverse_lazy("books:organization-list")

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.owner = self.request.user
        return super().form_valid(form)

    def users(self):
        return User.objects.all()


class OrganizationUpdateView(generic.UpdateView):
    template_name = "books/organization_create_or_update.html"
    model = Organization
    form_class = OrganizationForm
    success_url = reverse_lazy("books:organization-list")

    def get_queryset(self):
        # only current authenticated user organizations
        return organization_manager.get_user_organizations(self.request.user)

    def users(self):
        return User.objects.all()


class OrganizationDetailView(generic.DetailView):
    template_name = "books/organization_detail.html"
    model = Organization
    context_object_name = "organization"

    def get_queryset(self):
        # only current authenticated user organizations
        return organization_manager.get_user_organizations(self.request.user)

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        organization = self.get_object()
        ctx['invoices'] = (organization.invoices.all()
            .select_related('client', 'organization')
            .prefetch_related('lines'))
        ctx['bills'] = (organization.bills.all()
            .select_related('client', 'organization')
            .prefetch_related('lines'))
        return ctx


class OrganizationSelectionView(generic.DetailView):
    model = Organization

    def get_queryset(self):
        # only current authenticated user organizations
        return organization_manager.get_user_organizations(self.request.user)

    def post(self, request, *args, **kwargs):
        orga = self.get_object()
        organization_manager.set_selected_organization(self.request, orga)
        return HttpResponseRedirect(reverse('books:dashboard'))


class TaxRateListView(RestrictToSelectedOrganizationQuerySetMixin,
                      generic.ListView):
    template_name = "books/tax_rate_list.html"
    model = TaxRate
    context_object_name = "tax_rates"
    def get_queryset(self):
        return TaxRate.objects.filter(created_by=self.request.user)


class TaxRateCreateView(AutoSetSelectedOrganizationMixin,
                        generic.CreateView):
    template_name = "books/tax_rate_create_or_update.html"
    model = TaxRate
    form_class = TaxRateForm
    success_url = reverse_lazy("books:tax_rate-list")

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.created_by = self.request.user
        return super(TaxRateCreateView, self).form_valid(form)


class TaxRateUpdateView(AutoSetSelectedOrganizationMixin,
                        generic.UpdateView):
    template_name = "books/tax_rate_create_or_update.html"
    model = TaxRate
    form_class = TaxRateForm
    success_url = reverse_lazy("books:tax_rate-list")


class TaxRateDeleteView(generic.DeleteView):
    template_name = "_generics/delete_entity.html"
    model = TaxRate
    success_url = reverse_lazy('books:tax_rate-list')


class PaymentUpdateView(generic.UpdateView):
    template_name = "books/payment_create_or_update.html"
    model = Payment
    form_class = PaymentForm

    def get_success_url(self):
        related_obj = self.object.content_object
        if isinstance(related_obj, Invoice):
            return reverse("books:invoice-detail", args=[related_obj.pk])
        elif isinstance(related_obj, Bill):
            return reverse("books:bill-detail", args=[related_obj.pk])

        logger.warning("Unsupported related object '{}' for "
                       "payment '{}'".format(self.object, related_obj))
        return reverse("books:dashboard")


class PaymentDeleteView(generic.DeleteView):
    template_name = "_generics/delete_entity.html"
    model = Payment
    success_url = reverse_lazy('books:invoice-list')


class EstimateListView(RestrictToSelectedOrganizationQuerySetMixin,
                       SaleListQuerySetMixin,
                       generic.ListView):
    template_name = "books/estimate_list.html"
    model = Estimate
    context_object_name = "estimates"


class EstimateCreateView(AutoSetSelectedOrganizationMixin,
                         AbstractSaleCreateUpdateMixin,
                         generic.CreateView):
    template_name = "books/estimate_create_or_update.html"
    model = Estimate
    form_class = EstimateForm
    formset_class = EstimateLineFormSet
    success_url = reverse_lazy("books:estimate-list")

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        orga = organization_manager.get_selected_organization(self.request)
        self.restrict_fields_choices_to_organization(form, orga)
        return form

    def get_initial(self):
        initial = super().get_initial()

        orga = organization_manager.get_selected_organization(self.request)
        initial['number'] = EstimateNumberGenerator().next_number(orga)

        return initial

    def clients(self):
        return Client.objects.all()


class EstimateUpdateView(AutoSetSelectedOrganizationMixin,
                         AbstractSaleCreateUpdateMixin,
                         generic.UpdateView):
    template_name = "books/estimate_create_or_update.html"
    model = Estimate
    form_class = EstimateForm
    formset_class = EstimateLineFormSet
    success_url = reverse_lazy("books:estimate-list")


class EstimateDeleteView(generic.DeleteView):
    template_name = "_generics/delete_entity.html"

templates/books/_generics/item_list.html
{% load currency_filters status_filters %}

<table id="datatable" class="table table-responsive table-bordered table-striped" cellspacing="0" width="100%" style="width: 1142px;border-right-width: 0px;border-left-width: 0px;">
    <thead>
        <tr>
            <th class="text-center">#</th>
            <th class="text-center">Name</th>
            <th class="text-center">Description</th>
            <th class="text-center">Price</th>
            <th class="text-center">Quantity</th>
            <th class="text-center">Tax Rate</th>
            <th class="text-center">Actions</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <th class="text-center">#</th>
            <th class="text-center">Name</th>
            <th class="text-center">Description</th>
            <th class="text-center">Price</th>
            <th class="text-center">Quantity</th>
            <th class="text-center">Tax Rate</th>
            <th class="text-center">Actions</th>
        </tr>
    </tfoot>
    <tbody>
        {% for sale in sales %}
        <tr>
            <td class="text-center">{{ forloop.counter }}</td>
            <td class="text-center">{{ sale.name }}</td>
            <td class="text-center">{{ sale.description }}</td>
            <td class="text-center">{{ sale.unit_price_excl_tax|currency }}</td>
            <td class="text-center">{{ sale.quantity }}</td>
            <td class="text-center">{{ sale.tax_rate }}</td>
            <td class="text-center">
                <a href="{% url 'books:item-delete' pk=sale.pk %}" class="btn btn-danger btn-sm" role="button">Delete</a>
                {% if not hide_edit %}
                <a href="{% url 'books:item-edit' pk=sale.pk %}" class="btn btn-default btn-sm" role="button">Edit</a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

templates/books/_generics/sale_content.html
{% load currency_filters format_filters %}

<div class="row">
    <div class="col-xs-12 col-sm-6">
        <div class="card bg-dark">
            {% with client=object.from_client %}
            <div class="card-header">
                <h4 style="color:white;">From: <a href="{{ client.get_absolute_url }}">{{ client }}</a></h4>
            </div>
            <div class="card-body bg-light">
                <address>
                    <strong>{{ client }}</strong><br>
                    {{ client.full_address|linebreaksbr }}<br>
                </address>
            </div>
            {% endwith %}
        </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-xs-offset-2 text-right" style="margin-left: auto;">
        <div class="card bg-dark">
            {% with client=object.to_client %}
            <div class="card-header">
                <h4 style="color:white">To: <a href="{{ client.get_absolute_url }}">{{ client }}</a></h4>
            </div>
            <div class="card-body bg-light">
                <address>
                    <strong>{{ client.name }}</strong><br>
                    {{ client.full_address|linebreaksbr }}<br>
                </address>
            </div>
            {% endwith %}
        </div>
    </div>
</div>
<!-- / end client details section -->
<div class="table-responsive" style="margin-top:5%">
    <table class="table table-striped table-bordered">
        <thead>
            <tr class="row" style="margin-left: 0px; margin-right: 0px;">
                <th class="col-xs-1 col-sm-1">#</th>
                <th class="col-xs-2 col-sm-2">Label</th>
                <th class="col-xs-3 col-sm-2">Description</th>
                <th class="col-xs-2 col-sm-2">Unit (excl. tax)</th>
                <th class="col-xs-1 col-sm-1">Qt.</th>
                <th class="col-xs-1 col-sm-2">Tax rate</th>
                <th class="col-xs-2 col-sm-2 text-right">Amount</th>
            </tr>
        </thead>
        <tbody>
            {% for line in lines.all %}
            <tr class="row" style="margin-left: 0px; margin-right: 0px;">
                <td class="col-xs-1 col-sm-1">{{ forloop.counter }}</td>
                <td class="col-xs-2 col-sm-2">{{ line.label }}</td>
                <td class="col-xs-3 col-sm-2">{{ line.description|linebreaks }}</td>
                <td class="col-xs-2 col-sm-2">{{ line.unit_price_excl_tax|currency }}</td>
                <td class="col-xs-1 col-sm-1">{{ line.quantity }}</td>
                <td class="col-xs-1 col-sm-2">{{ line.tax_rate.rate|percentage }}</td>
                <td class="col-xs-2 col-sm-2 text-right">{{ line.line_price_excl_tax|currency }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<div class="row text-right">
    <div class="col-xs-2 col-xs-offset-8" style="margin-left: auto;">
        <p>
            <strong>
                Sub Total : <br>
                Tax : <br>
                Total : <br>
            </strong>
        </p>
    </div>
    <div class="col-xs-2">
        <strong>
            {{ object.total_excl_tax|currency }} <br>
            {{ object.total_tax|currency }} <br>
            {{ object.total_incl_tax|currency }} <br>
        </strong>
    </div>
</div>

templates/books/_generics/sale_detail.html
{% load currency_filters bootstrap3 form_filters check_filters check_tags %}

<div class="row placeholders">
    <div class="col-xs-6 col-sm-4">
        <div class="figure">
            <h4>{{ object.total_incl_tax|currency|default:"-" }}</h4>
            <span class="text-muted">Total (incl. tax)</span>
        </div>
    </div>
    <div class="col-xs-6 col-sm-4">
        <div class="figure">
            <h4>{{ object.total_excl_tax|currency|default:"-" }}</h4>
            <span class="text-muted">Total (excl. tax)</span>
        </div>
    </div>
    <div class="col-xs-6 col-sm-4">
        <div class="figure">
            <h4>{{ object.total_tax|currency }}</h4>
            <span class="text-muted">Tax</span>
        </div>
    </div>
    <div class="col-xs-6 col-sm-4">
        <div class="figure">
            <h4>{{ object.date_issued|default:"-" }}</h4>
            <span class="text-muted">Date issued</span>
        </div>
    </div>
    <div class="col-xs-6 col-sm-4">
        <div class="figure">
            <h4>{{ object.total_due_incl_tax|currency|default:"-" }}</h4>
            <span class="text-muted">Total still due (incl. tax)</span>
        </div>
    </div>
    <div class="col-xs-6 col-sm-4">
        <div class="figure">
            <h4>{{ object.date_dued|default:"-" }}</h4>
            <span class="text-muted">Date dued</span>
        </div>
    </div>
</div>

{% if checklist %}
<h3 class="page-header">Checklist</h3>
<div class="row">
    <div class="col-xs-6 col-sm-4">
        <div class="list-group check-list">
        {% for check in checklist %}
            <div class="list-group-item list-group-item-{{ check|level_to_css_classname }}">
                {% render_check check %}
            </div>
        {% endfor %}
        </div>
    </div>
</div>
{% endif %}

<h3 class="page-header">Content</h3>
{% include "books/_generics/sale_content.html" with object=object %}


{% if payment_form %}
<div class="panel panel-default" style="padding-bottom:5%">
    <div class="panel-heading">
            <hr>
        <h4>Payments</h4>
    </div>

    {% include "books/_partials/payment_list.html" with payments=payments %}

    <div class="panel-footer">
        <form action="." method="post" class="form">
            {% csrf_token %}

            {{ payment_form.non_field_errors }}
            <div class="row">
                <div class="col-md-2">
                    {% bootstrap_field payment_form.date_paid show_label=False %}
                </div>
                <div class="col-md-2">
                    {% bootstrap_field payment_form.reference show_label=False %}
                </div>
                <div class="col-md-4">
                    {% bootstrap_field payment_form.detail show_label=False %}
                </div>
                <div class="col-md-2">
                    {% bootstrap_field payment_form.amount show_label=False %}
                </div>
                <div class="col-md-2 text-right">
                    <button type="submit" class="btn btn-success">Add payment</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endif %}

templates/books/_generics/sale_list.html
{% load currency_filters status_filters %}
<table id="datatable" class="table table-responsive table-bordered table-striped" style="width: 100%" style="width: 1142px;border-right-width: 0px;border-left-width: 0px;">
    <thead>
        <tr style="margin-left: 0px; margin-right: 0px;">
            <th class="text-center">#</th>
            {% if detailed %}
            <th class="text-center">Client</th>
            <th class="text-center">Description</th>
            <th class="text-center">Total</th>
            <th class="text-center">Actions</th>
            {% else %}
            <th class="text-center">Client</th>
            <th class="text-center">Total</th>
            <th class="text-center">Actions</th>
            {% endif %}
        </tr>
    </thead>
    <tfoot>
        <tr style="margin-left: 0px; margin-right: 0px;">
            <th class="text-center">#</th>
            {% if detailed %}
            <th class="text-center">Client</th>
            <th class="text-center">Description</th>
            <th class="text-center">Total</th>
            <th class="text-center">Actions</th>
            {% else %}
            <th class="text-center">Client</th>
            <th class="text-center">Total</th>
            <th class="text-center">Actions</th>
            {% endif %}
        </tr>
    </tfoot>
    <tbody>
        {% for sale in sales %}
        <tr style="margin-left: 0px; margin-right: 0px;">
            <td class="text-center">{{ sale.number }}</td>
            {% if detailed %}
            <td class="text-center">{{ sale.client }}</td>
            <td class="text-center">{{ sale.description }}</td>
            <td class="text-center">{{ sale.total_excl_tax|currency }}</td>
            <td class="text-center">
                <a href="{{ sale.get_detail_url }}" class="btn btn-success btn-sm" role="button">View</a>
                {% if not hide_edit %}
                <a href="{{ sale.get_edit_url }}" class="btn btn-default btn-sm" role="button">Edit</a>
                {% endif %}
            </td>
            {% else %}
            <td class="text-center">{{ sale.client }}</td>
            <td class="text-center">{{ sale.total_excl_tax|currency }}</td>
            <td class="text-center">
                <a href="{{ sale.get_detail_url }}" class="btn btn-success btn-sm" role="button">View</a>
                {% if not hide_edit %}
                <a href="{{ sale.get_edit_url }}" class="btn btn-default btn-sm" role="button">Edit</a>
                {% endif %}
            </td>
            {% endif %}
        </tr>
        {% endfor %}
    </tbody>
</table>

templates/books/_generics/sale_list2.html
{% load currency_filters status_filters %}
<div class="table-responsive-xl">
<table class="table table-bordered table-striped" cellspacing="0" width="100%">
    <thead>
        <tr class="row" style="margin-left: 0px; width: 540px; margin-right: 0px; ">
            <th class="col-xs-1">#</th>
            <th class="col-xs-3">Client</th>
            {% if detailed %}
                <th class="col-xs-4">Description</th>
                <th class="col-xs-2">Total</th>
                <th class="text-right col-xs-2">Actions</th>
            {% else %}
                <th class="col-xs-4">Total</th>
                <th class="text-right col-xs-4">Actions</th>
            {% endif %}
        </tr>
    </thead>
    <tbody>
        {% for sale in sales %}
        <tr class="row {{ sale|status_to_css_classname }}" style="margin-left: 0px; width: 540px; margin-right: 0px; ">
            <td class="col-xs-1">{{ sale.number }}</td>
            <td class="col-xs-3">{{ sale.client }}</td>
            {% if detailed %}
            <td class="col-xs-3">{{ sale.description }}</td>
            {% endif %}
            <td class="col-xs-2">{{ sale.total_excl_tax|currency }}</td>
            <td class="text-right col-xs-3">
                <a href="{{ sale.get_detail_url }}" class="btn btn-success btn-sm" role="button">View</a>
                {% if not hide_edit %}
                <a href="{{ sale.get_edit_url }}" class="btn btn-default btn-sm" role="button">Edit</a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>